// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.8
// source: api/proto/timeline/timeline.proto

package timeline

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RequestTimeline struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ProcessId string `protobuf:"bytes,1,opt,name=processId,proto3" json:"processId,omitempty"`
	// Types that are assignable to Timeline:
	//
	//	*RequestTimeline_SinceTimestamp
	Timeline isRequestTimeline_Timeline `protobuf_oneof:"timeline"`
}

func (x *RequestTimeline) Reset() {
	*x = RequestTimeline{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_timeline_timeline_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RequestTimeline) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestTimeline) ProtoMessage() {}

func (x *RequestTimeline) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_timeline_timeline_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestTimeline.ProtoReflect.Descriptor instead.
func (*RequestTimeline) Descriptor() ([]byte, []int) {
	return file_api_proto_timeline_timeline_proto_rawDescGZIP(), []int{0}
}

func (x *RequestTimeline) GetProcessId() string {
	if x != nil {
		return x.ProcessId
	}
	return ""
}

func (m *RequestTimeline) GetTimeline() isRequestTimeline_Timeline {
	if m != nil {
		return m.Timeline
	}
	return nil
}

func (x *RequestTimeline) GetSinceTimestamp() float64 {
	if x, ok := x.GetTimeline().(*RequestTimeline_SinceTimestamp); ok {
		return x.SinceTimestamp
	}
	return 0
}

type isRequestTimeline_Timeline interface {
	isRequestTimeline_Timeline()
}

type RequestTimeline_SinceTimestamp struct {
	SinceTimestamp float64 `protobuf:"fixed64,2,opt,name=sinceTimestamp,proto3,oneof"`
}

func (*RequestTimeline_SinceTimestamp) isRequestTimeline_Timeline() {}

type ResponseTimeline struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ProcessId string `protobuf:"bytes,1,opt,name=processId,proto3" json:"processId,omitempty"`
	Error     string `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	Items     []byte `protobuf:"bytes,3,opt,name=items,proto3" json:"items,omitempty"`
}

func (x *ResponseTimeline) Reset() {
	*x = ResponseTimeline{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_timeline_timeline_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ResponseTimeline) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResponseTimeline) ProtoMessage() {}

func (x *ResponseTimeline) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_timeline_timeline_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResponseTimeline.ProtoReflect.Descriptor instead.
func (*ResponseTimeline) Descriptor() ([]byte, []int) {
	return file_api_proto_timeline_timeline_proto_rawDescGZIP(), []int{1}
}

func (x *ResponseTimeline) GetProcessId() string {
	if x != nil {
		return x.ProcessId
	}
	return ""
}

func (x *ResponseTimeline) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *ResponseTimeline) GetItems() []byte {
	if x != nil {
		return x.Items
	}
	return nil
}

var File_api_proto_timeline_timeline_proto protoreflect.FileDescriptor

var file_api_proto_timeline_timeline_proto_rawDesc = []byte{
	0x0a, 0x21, 0x61, 0x70, 0x69, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x74, 0x69, 0x6d, 0x65,
	0x6c, 0x69, 0x6e, 0x65, 0x2f, 0x74, 0x69, 0x6d, 0x65, 0x6c, 0x69, 0x6e, 0x65, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x08, 0x74, 0x69, 0x6d, 0x65, 0x6c, 0x69, 0x6e, 0x65, 0x22, 0x65, 0x0a,
	0x0f, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x54, 0x69, 0x6d, 0x65, 0x6c, 0x69, 0x6e, 0x65,
	0x12, 0x1c, 0x0a, 0x09, 0x70, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x49, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x09, 0x70, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x49, 0x64, 0x12, 0x28,
	0x0a, 0x0e, 0x73, 0x69, 0x6e, 0x63, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x01, 0x48, 0x00, 0x52, 0x0e, 0x73, 0x69, 0x6e, 0x63, 0x65, 0x54,
	0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x42, 0x0a, 0x0a, 0x08, 0x74, 0x69, 0x6d, 0x65,
	0x6c, 0x69, 0x6e, 0x65, 0x22, 0x5c, 0x0a, 0x10, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x54, 0x69, 0x6d, 0x65, 0x6c, 0x69, 0x6e, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x70, 0x72, 0x6f, 0x63,
	0x65, 0x73, 0x73, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x70, 0x72, 0x6f,
	0x63, 0x65, 0x73, 0x73, 0x49, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x12, 0x14, 0x0a, 0x05,
	0x69, 0x74, 0x65, 0x6d, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x05, 0x69, 0x74, 0x65,
	0x6d, 0x73, 0x42, 0x2c, 0x5a, 0x2a, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d,
	0x2f, 0x53, 0x61, 0x6e, 0x6e, 0x72, 0x6f, 0x78, 0x2f, 0x74, 0x72, 0x61, 0x64, 0x65, 0x70, 0x69,
	0x70, 0x65, 0x2f, 0x67, 0x72, 0x70, 0x63, 0x2f, 0x74, 0x69, 0x6d, 0x65, 0x6c, 0x69, 0x6e, 0x65,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_api_proto_timeline_timeline_proto_rawDescOnce sync.Once
	file_api_proto_timeline_timeline_proto_rawDescData = file_api_proto_timeline_timeline_proto_rawDesc
)

func file_api_proto_timeline_timeline_proto_rawDescGZIP() []byte {
	file_api_proto_timeline_timeline_proto_rawDescOnce.Do(func() {
		file_api_proto_timeline_timeline_proto_rawDescData = protoimpl.X.CompressGZIP(file_api_proto_timeline_timeline_proto_rawDescData)
	})
	return file_api_proto_timeline_timeline_proto_rawDescData
}

var file_api_proto_timeline_timeline_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_api_proto_timeline_timeline_proto_goTypes = []interface{}{
	(*RequestTimeline)(nil),  // 0: timeline.RequestTimeline
	(*ResponseTimeline)(nil), // 1: timeline.ResponseTimeline
}
var file_api_proto_timeline_timeline_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_proto_timeline_timeline_proto_init() }
func file_api_proto_timeline_timeline_proto_init() {
	if File_api_proto_timeline_timeline_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_api_proto_timeline_timeline_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RequestTimeline); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_proto_timeline_timeline_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ResponseTimeline); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_api_proto_timeline_timeline_proto_msgTypes[0].OneofWrappers = []interface{}{
		(*RequestTimeline_SinceTimestamp)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_api_proto_timeline_timeline_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_api_proto_timeline_timeline_proto_goTypes,
		DependencyIndexes: file_api_proto_timeline_timeline_proto_depIdxs,
		MessageInfos:      file_api_proto_timeline_timeline_proto_msgTypes,
	}.Build()
	File_api_proto_timeline_timeline_proto = out.File
	file_api_proto_timeline_timeline_proto_rawDesc = nil
	file_api_proto_timeline_timeline_proto_goTypes = nil
	file_api_proto_timeline_timeline_proto_depIdxs = nil
}
