// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.8
// source: api/proto/tradepipe.proto

package pb

import (
	context "context"
	login "github.com/Sannrox/tradepipe/grpc/pb/login"
	portfolio "github.com/Sannrox/tradepipe/grpc/pb/portfolio"
	savingsplan "github.com/Sannrox/tradepipe/grpc/pb/savingsplan"
	timeline "github.com/Sannrox/tradepipe/grpc/pb/timeline"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// TradePipeClient is the client API for TradePipe service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TradePipeClient interface {
	Alive(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*Alive, error)
	Login(ctx context.Context, in *login.Credentials, opts ...grpc.CallOption) (*login.ProcessId, error)
	Verify(ctx context.Context, in *login.TwoFAAsks, opts ...grpc.CallOption) (*login.TwoFAReturn, error)
	Timeline(ctx context.Context, in *timeline.RequestTimeline, opts ...grpc.CallOption) (*timeline.ResponseTimeline, error)
	TimelineDetails(ctx context.Context, in *timeline.RequestTimeline, opts ...grpc.CallOption) (*timeline.ResponseTimeline, error)
	Positions(ctx context.Context, in *portfolio.RequestPositions, opts ...grpc.CallOption) (*portfolio.ResponsePositions, error)
	SavingsPlans(ctx context.Context, in *savingsplan.RequestSavingsplan, opts ...grpc.CallOption) (*savingsplan.ResponseSavingsplan, error)
}

type tradePipeClient struct {
	cc grpc.ClientConnInterface
}

func NewTradePipeClient(cc grpc.ClientConnInterface) TradePipeClient {
	return &tradePipeClient{cc}
}

func (c *tradePipeClient) Alive(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*Alive, error) {
	out := new(Alive)
	err := c.cc.Invoke(ctx, "/pb.TradePipe/Alive", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tradePipeClient) Login(ctx context.Context, in *login.Credentials, opts ...grpc.CallOption) (*login.ProcessId, error) {
	out := new(login.ProcessId)
	err := c.cc.Invoke(ctx, "/pb.TradePipe/Login", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tradePipeClient) Verify(ctx context.Context, in *login.TwoFAAsks, opts ...grpc.CallOption) (*login.TwoFAReturn, error) {
	out := new(login.TwoFAReturn)
	err := c.cc.Invoke(ctx, "/pb.TradePipe/Verify", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tradePipeClient) Timeline(ctx context.Context, in *timeline.RequestTimeline, opts ...grpc.CallOption) (*timeline.ResponseTimeline, error) {
	out := new(timeline.ResponseTimeline)
	err := c.cc.Invoke(ctx, "/pb.TradePipe/Timeline", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tradePipeClient) TimelineDetails(ctx context.Context, in *timeline.RequestTimeline, opts ...grpc.CallOption) (*timeline.ResponseTimeline, error) {
	out := new(timeline.ResponseTimeline)
	err := c.cc.Invoke(ctx, "/pb.TradePipe/TimelineDetails", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tradePipeClient) Positions(ctx context.Context, in *portfolio.RequestPositions, opts ...grpc.CallOption) (*portfolio.ResponsePositions, error) {
	out := new(portfolio.ResponsePositions)
	err := c.cc.Invoke(ctx, "/pb.TradePipe/Positions", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tradePipeClient) SavingsPlans(ctx context.Context, in *savingsplan.RequestSavingsplan, opts ...grpc.CallOption) (*savingsplan.ResponseSavingsplan, error) {
	out := new(savingsplan.ResponseSavingsplan)
	err := c.cc.Invoke(ctx, "/pb.TradePipe/SavingsPlans", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TradePipeServer is the server API for TradePipe service.
// All implementations must embed UnimplementedTradePipeServer
// for forward compatibility
type TradePipeServer interface {
	Alive(context.Context, *emptypb.Empty) (*Alive, error)
	Login(context.Context, *login.Credentials) (*login.ProcessId, error)
	Verify(context.Context, *login.TwoFAAsks) (*login.TwoFAReturn, error)
	Timeline(context.Context, *timeline.RequestTimeline) (*timeline.ResponseTimeline, error)
	TimelineDetails(context.Context, *timeline.RequestTimeline) (*timeline.ResponseTimeline, error)
	Positions(context.Context, *portfolio.RequestPositions) (*portfolio.ResponsePositions, error)
	SavingsPlans(context.Context, *savingsplan.RequestSavingsplan) (*savingsplan.ResponseSavingsplan, error)
	mustEmbedUnimplementedTradePipeServer()
}

// UnimplementedTradePipeServer must be embedded to have forward compatible implementations.
type UnimplementedTradePipeServer struct {
}

func (UnimplementedTradePipeServer) Alive(context.Context, *emptypb.Empty) (*Alive, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Alive not implemented")
}
func (UnimplementedTradePipeServer) Login(context.Context, *login.Credentials) (*login.ProcessId, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Login not implemented")
}
func (UnimplementedTradePipeServer) Verify(context.Context, *login.TwoFAAsks) (*login.TwoFAReturn, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Verify not implemented")
}
func (UnimplementedTradePipeServer) Timeline(context.Context, *timeline.RequestTimeline) (*timeline.ResponseTimeline, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Timeline not implemented")
}
func (UnimplementedTradePipeServer) TimelineDetails(context.Context, *timeline.RequestTimeline) (*timeline.ResponseTimeline, error) {
	return nil, status.Errorf(codes.Unimplemented, "method TimelineDetails not implemented")
}
func (UnimplementedTradePipeServer) Positions(context.Context, *portfolio.RequestPositions) (*portfolio.ResponsePositions, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Positions not implemented")
}
func (UnimplementedTradePipeServer) SavingsPlans(context.Context, *savingsplan.RequestSavingsplan) (*savingsplan.ResponseSavingsplan, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SavingsPlans not implemented")
}
func (UnimplementedTradePipeServer) mustEmbedUnimplementedTradePipeServer() {}

// UnsafeTradePipeServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TradePipeServer will
// result in compilation errors.
type UnsafeTradePipeServer interface {
	mustEmbedUnimplementedTradePipeServer()
}

func RegisterTradePipeServer(s grpc.ServiceRegistrar, srv TradePipeServer) {
	s.RegisterService(&TradePipe_ServiceDesc, srv)
}

func _TradePipe_Alive_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TradePipeServer).Alive(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.TradePipe/Alive",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TradePipeServer).Alive(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _TradePipe_Login_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(login.Credentials)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TradePipeServer).Login(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.TradePipe/Login",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TradePipeServer).Login(ctx, req.(*login.Credentials))
	}
	return interceptor(ctx, in, info, handler)
}

func _TradePipe_Verify_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(login.TwoFAAsks)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TradePipeServer).Verify(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.TradePipe/Verify",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TradePipeServer).Verify(ctx, req.(*login.TwoFAAsks))
	}
	return interceptor(ctx, in, info, handler)
}

func _TradePipe_Timeline_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(timeline.RequestTimeline)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TradePipeServer).Timeline(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.TradePipe/Timeline",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TradePipeServer).Timeline(ctx, req.(*timeline.RequestTimeline))
	}
	return interceptor(ctx, in, info, handler)
}

func _TradePipe_TimelineDetails_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(timeline.RequestTimeline)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TradePipeServer).TimelineDetails(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.TradePipe/TimelineDetails",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TradePipeServer).TimelineDetails(ctx, req.(*timeline.RequestTimeline))
	}
	return interceptor(ctx, in, info, handler)
}

func _TradePipe_Positions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(portfolio.RequestPositions)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TradePipeServer).Positions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.TradePipe/Positions",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TradePipeServer).Positions(ctx, req.(*portfolio.RequestPositions))
	}
	return interceptor(ctx, in, info, handler)
}

func _TradePipe_SavingsPlans_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(savingsplan.RequestSavingsplan)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TradePipeServer).SavingsPlans(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.TradePipe/SavingsPlans",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TradePipeServer).SavingsPlans(ctx, req.(*savingsplan.RequestSavingsplan))
	}
	return interceptor(ctx, in, info, handler)
}

// TradePipe_ServiceDesc is the grpc.ServiceDesc for TradePipe service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TradePipe_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pb.TradePipe",
	HandlerType: (*TradePipeServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Alive",
			Handler:    _TradePipe_Alive_Handler,
		},
		{
			MethodName: "Login",
			Handler:    _TradePipe_Login_Handler,
		},
		{
			MethodName: "Verify",
			Handler:    _TradePipe_Verify_Handler,
		},
		{
			MethodName: "Timeline",
			Handler:    _TradePipe_Timeline_Handler,
		},
		{
			MethodName: "TimelineDetails",
			Handler:    _TradePipe_TimelineDetails_Handler,
		},
		{
			MethodName: "Positions",
			Handler:    _TradePipe_Positions_Handler,
		},
		{
			MethodName: "SavingsPlans",
			Handler:    _TradePipe_SavingsPlans_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/proto/tradepipe.proto",
}
