#!/usr/bin/env sh

set -eux

PREFIX="github.com/Sannrox/tradepipe"

find ./api/ -type f  -iname "*.proto" > ./protos.txt 
while IFS= read -r file ; do \
    protoc --go_out=.  --go_opt=module=$PREFIX \
    --go-grpc_out=.  --go-grpc_opt=module=$PREFIX\
    $file; \
done < ./protos.txt
rm ./protos.txt

