openapi: "3.0.0"
info:
  version: 1.0.0
  title: tradepipe-api
  description: This Api is used to manage the tradepipe application
servers:
  - url: http://localhost:8080
paths:
  /alive:
    get:
      summary: Status
      description: Status of the server
      operationId: alive
      responses:
        "200":
          description: Server available
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Alive"
        "401":
          description: Server forbidden
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Alive"
        "500":
          $ref: "#/components/responses/InternalServerError"
  /login:
    post:
      summary: Login
      description: Login to the application
      operationId: login
      requestBody:
        description: Login credentials
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Login"
      responses:
        "200":
          description: Login successful
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ProcessId"
        "401":
          description: Login failed
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ProcessId"
        "500":
          $ref: "#/components/responses/InternalServerError"
  /{processId}/verify:
    post:
      summary: Verify
      description: Verify the user
      operationId: verify
      parameters:
        - in: path
          name: processId
          schema:
            type: string
          required: true
      requestBody:
        description: Login credentials
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Verify"
      responses:
        "200":
          description: Verify successful
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Verified"
        "401":
          description: Verify failed
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Verified"
        "500":
          $ref: "#/components/responses/InternalServerError"
  /{processId}/timeline:
    get:
      summary: timeline
      description: Loads the complete timeline
      operationId: timeline
      parameters:
        - in: path
          name: processId
          schema:
            type: string
          required: true
        - name: since
          in: query
          schema:
            type: number
            format: double
      responses:
        "200":
          description: Timeline successful
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Timeline"
        "401":
          description: Timeline failed
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Timeline"
        "500":
          $ref: "#/components/responses/InternalServerError"
  /{processId}/timelinedetails:
    get:
      summary: timelinedetails
      description: Loads the complete timeline details
      operationId: timelineDetails
      parameters:
        - in: path
          name: processId
          schema:
            type: string
          required: true
        - name: since
          in: query
          schema:
            type: number
            format: double
      responses:
        "200":
          description: Timeline successful
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/TimelineDetails"
        "401":
          description: Timeline failed
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/TimelineDetails"
        "500":
          $ref: "#/components/responses/InternalServerError"
  /{processId}/positions:
    get:
      summary: positions
      description: Loads your positions
      operationId: positions
      parameters:
        - in: path
          name: processId
          schema:
            type: string
          required: true
      responses:
        "200":
          description: Positions successful
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Positions"
        "401":
          description: Positions failed
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Positions"
        "500":
          $ref: "#/components/responses/InternalServerError"
  /{processId}/savingsplan:
    get:
      summary: savingsplans
      description: Load you savingsplans
      operationId: savingsplans
      parameters:
        - in: path
          name: processId
          schema:
            type: string
          required: true
      responses:
        "200":
          description: Savingsplans successful
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Savingsplans"
        "401":
          description: Savingsplans failed
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Savingsplans"
        "500":
          $ref: "#/components/responses/InternalServerError"
components:
  schemas:
    Login:
      required:
        - number
        - pin
      type: object
      properties:
        number:
          type: string
        pin:
          type: string
    ProcessId:
      type: string
    Verify:
      required:
        - token
      type: object
      properties:
        token:
          type: string
    Verified:
      type: object
      properties:
        message:
          type: string
    Timeline:
      required:
        - timeline
      type: object
      properties:
        message:
          type: string
        timeline:
          type: array
    TimelineDetails:
      required:
        - timelineDetails
      type: object
      properties:
        message:
          type: string
        timelineDetails:
          type: array
    Positions:
      required:
        - positions
      type: object
      properties:
        message:
          type: string
        positions:
          type: array
    Savingsplans:
      required:
        - savingsplans
      type: object
      properties:
        message:
          type: string
        savingsplans:
          type: array
    Alive:
      type: object
      properties:
        status:
          type: string
        serverTime:
          type: integer
          format: int64
    ErrorModel:
      type: object
      required:
        - message
      properties:
        message:
          type: string
  responses:
    InternalServerError:
      description: Internal Server Error
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/ErrorModel"
