name: Build and Release


on:
  push:
    branches: []
# on:
#   create:
#     tags:
#       - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build Go binary
        run: ./build/release-images.sh

      - name: Archive tradegrpc linux amd64
        uses: actions/upload-artifact@v2
        with:
          name: tradegrpc-linux-amd64
          path: _output/bin/linux/amd64/tradegrpc


      - name: Archive tradegrpc linux arm64
        uses: actions/upload-artifact@v2
        with:
          name: tradegrpc-linux-arm64
          path: _output/bin/linux/arm64/tradegrpc

      # - name: Push Docker container to registry
      #   uses: docker/build-push-action@v2
      #   with:
      #     context: .
      #     push: true
      #     tags: myapp:${{ github.ref }}
