name: Test and validate

on:
  push:
    branches: []

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - uses: actions/setup-go@v4
        with:
          go-version: '>=1.17.0'

      - name: Validate code
        run: make validate

  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - uses: actions/setup-go@v4
        with:
          go-version: '>=1.17.0' 
      - name: Run tests
        run: make test || true
      - name: Upload test reports 
        uses: actions/upload-artifact@v2
        with:
          name: test-reports
          path: |
            _output/test-results/unit-tests.xml