name: Test and validate

on:
  push:
    branches: [ "main" ]
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [ "main" ]
  schedule:
    - cron: '40 22 * * 6'

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - uses: actions/setup-go@v4
        with:
          go-version: '>=1.17.0'

      - name: Validate code
        run: make validate

  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - uses: actions/setup-go@v4
        with:
          go-version: '>=1.17.0'
      - name: Run tests
        run: make test
      - name: Upload test reports
        uses: actions/upload-artifact@v2
        if: success() || failure()
        with:
          name: test-reports
          path: |
            _output/test-results/unit-tests.xml
