name: Test and validate

on:
  push:
    branches: []

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2


      - name: Validate code
        uses: actions/setup-go@v4
        with:
          go-version: '>=1.17.0'
        run: make validate

  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
  
      - name: Run tests
        run: make test
